version: "3"

services:

  amqp:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  sender:
    build: ./sender/
    restart: on-failure
    depends_on:
      - amqp
    links:
      - amqp