package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"github.com/sinyavcev/microservices/receiver/graphql/graph/model"
	"go.mongodb.org/mongo-driver/bson"
)

// Stocks is the resolver for the stocks field.
func (r *queryResolver) Stocks(ctx context.Context, symbol *string) (stocks []*model.Stock, err error) {
	result, err := r.Database.Collection("test").Find(ctx, bson.M{"symbol": symbol})
	if err != nil {
		return nil, err
	}

	err = result.All(ctx, &stocks)
	if err != nil {
		return nil, err
	}

	return stocks, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
