// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Stock struct {
	Symbol string `json:"Symbol"`
	Open   string `json:"Open"`
	High   string `json:"High"`
	Low    string `json:"Low"`
	Day    string `json:"Day"`
}
